//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace n01352022_bonus_assignment {
    
    
    public partial class bonus_raffle_bundle_assignment_3 {
        
        /// <summary>
        /// raffle_bundle_purchasing_form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm raffle_bundle_purchasing_form;
        
        /// <summary>
        /// raffle_ticket_purchase_amount_input control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox raffle_ticket_purchase_amount_input;
        
        /// <summary>
        /// raffle_bundle_purchase_display_box control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl raffle_bundle_purchase_display_box;
    }
}
